In [7]:
import numpy as np
np.array([2,4,56,422,32,1]) 

array([  2,   4,  56, 422,  32,   1])

In [7]:
import numpy as np
np.array([2,4,56,422,32,1]) 

array([  2,   4,  56, 422,  32,   1])

In [2]:
a = np.array([2,4,56,422,32,1]) 
print(a) 

[  2   4  56 422  32   1]


In [3]:
type(a)

numpy.ndarray

In [4]:
new = np.array([[45,34,22,2],[24,55,3,22]])
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [10]:
np.array ( [[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])
            

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

In [11]:
np.array([11,23,44] , dtype =float)

array([11., 23., 44.])

In [12]:
np.array([11,23,44] , dtype =bool)

array([ True,  True,  True])

In [13]:
np.array([11,23,44] , dtype =complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

In [14]:
np.arange(1,25) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [15]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [16]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
np.arange(1,13).reshape(3,4) 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.random.random((4,3))

array([[0.73730675, 0.77584257, 0.03732035],
       [0.37696829, 0.98043507, 0.49411327],
       [0.59239812, 0.9714019 , 0.68471572],
       [0.24185931, 0.76420392, 0.59065317]])

In [22]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
a1 = np.arange(10)

In [26]:
a

array([  2,   4,  56, 422,  32,   1])

In [27]:
a2 =np.arange(12, dtype =float).reshape(3,4)

In [28]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [29]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64


In [36]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)

In [37]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
z1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [40]:
z1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [41]:
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [42]:
z1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [43]:
z1+z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [44]:
z1<2

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [45]:
z1>2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [46]:

k1 = np.random.random((3,3))
k1 = np.round(k1*100)
k1

array([[65., 64., 78.],
       [86., 57., 67.],
       [10., 87., 30.]])

In [47]:
np.max(k1)

np.float64(87.0)

In [48]:
np.min(k1)

np.float64(10.0)

In [49]:
np.prod(k1)

np.float64(2781483898752000.0)

In [50]:
s2 = np.arange(12).reshape(3,4)
s3 = np.arange(12,24).reshape(4,3)

In [51]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [53]:
np.dot(s2,s3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [54]:
arr = np.array([1.2, 2.7, 3.5, 4.9])
rounded_arr = np.round(arr)
print(rounded_arr)

[1. 3. 4. 5.]


In [55]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [56]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [59]:
p2[1,2]

np.int64(6)

In [60]:
p3[0,0,0]

np.int64(0)

In [61]:
p1[2:5]


array([2, 3, 4])

In [62]:
p2[1:3 ,1:3] 

array([[ 5,  6],
       [ 9, 10]])

In [63]:
p3 = np.arange(27).reshape(3,3,3)
p3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [64]:
p3[::2]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [65]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
for i in p1:
 print(i)

0
1
2
3
4
5
6
7
8
9
